name: xor
version: 0.2.1
author: Jeremi Gendron <gendronjeremi@gmail.com>
homepage: https://github.com/jeremigendron
repository: https://github.com/jeremigendron/xor
description: xor IntList's together and return a new List<int>; useful for cryptographic functions.

environment:
  sdk: '>=2.12.0 <3.0.0' 

dev_dependencies:
  test: ^1.21.1
  hex: ^0.2.0

